package com.hjkj.hyjc.model.admin;

// default package
// Generated 2016-8-19 22:18:42 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfDictionary generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_DICTIONARY")
public class SysDictionary implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private String dicId;
    private int version;
    private String dicCode;
    private String dicTitle;
    private String memo;
    private char mark;
    private String maker;
    private Date maketime;
    private String updater;
    private Date updatetime;

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "dic_id", unique = true, nullable = false)
    public String getDicId() {
        return this.dicId;
    }

    public void setDicId(String dicId) {
        this.dicId = dicId;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "dic_code", length = 100)
    public String getDicCode() {
        return this.dicCode;
    }

    public void setDicCode(String dicCode) {
        this.dicCode = dicCode;
    }

    @Column(name = "dic_title", length = 100)
    public String getDicTitle() {
        return this.dicTitle;
    }

    public void setDicTitle(String dicTitle) {
        this.dicTitle = dicTitle;
    }

    @Column(name = "memo", length = 500)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "mark", nullable = false, length = 1)
    public char getMark() {
        return this.mark;
    }

    public void setMark(char mark) {
        this.mark = mark;
    }

    @Column(name = "maker", nullable = false, length = 50)
    public String getMaker() {
        return this.maker;
    }

    public void setMaker(String maker) {
        this.maker = maker;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "maketime", nullable = false, length = 19)
    public Date getMaketime() {
        return this.maketime;
    }

    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    @Column(name = "updater", nullable = false, length = 50)
    public String getUpdater() {
        return this.updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", nullable = false, length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

}
