package com.hjkj.hyjc.model.admin;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfDepartment generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_DEPARTMENT")
public class SysDepartment implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private String deptId;
    private int version;
    private String deptName;
    private Integer deptLevel;
    private String status;
    private String parentDeptId;
    private String memo;
    private String mark;
    private String maker;
    private Date maketime;
    private String updater;
    private Date updatetime;
    private String deptType;
    private String deptRange;
    private String ruleCode;
    private String deptTel;
    private String deptAddress;
    private String deptCode;
    private String deptGrade;

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "dept_id", unique = true, nullable = false)
    public String getDeptId() {
        return this.deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "status", length = 1)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "dept_name", nullable = false, length = 200)
    public String getDeptName() {
        return this.deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    @Column(name = "dept_level", nullable = false)
    public Integer getDeptLevel() {
        return this.deptLevel;
    }

    public void setDeptLevel(Integer deptLevel) {
        this.deptLevel = deptLevel;
    }

    @Column(name = "parent_dept_id", length = 100)
    public String getParentDeptId() {
        return this.parentDeptId;
    }

    public void setParentDeptId(String parentDeptId) {
        this.parentDeptId = parentDeptId;
    }

    @Column(name = "memo", length = 500)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "mark", nullable = false, length = 1)
    public String getMark() {
        return this.mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    @Column(name = "maker", nullable = false, length = 50)
    public String getMaker() {
        return this.maker;
    }

    public void setMaker(String maker) {
        this.maker = maker;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "maketime", nullable = false, length = 19)
    public Date getMaketime() {
        return this.maketime;
    }

    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    @Column(name = "updater", nullable = false, length = 50)
    public String getUpdater() {
        return this.updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", nullable = false, length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Column(name = "DEPT_TYPE", nullable = false, length = 200)
	public String getDeptType() {
		return deptType;
	}

	public void setDeptType(String deptType) {
		this.deptType = deptType;
	}

	@Column(name = "DEPT_RANGE", nullable = false, length = 200)
	public String getDeptRange() {
		return deptRange;
	}

	public void setDeptRange(String deptRange) {
		this.deptRange = deptRange;
	}

	@Column(name = "RULE_CODE", nullable = false, length = 200)
	public String getRuleCode() {
		return ruleCode;
	}

	public void setRuleCode(String ruleCode) {
		this.ruleCode = ruleCode;
	}

	@Column(name = "DEPT_TEL", nullable = false, length = 200)
	public String getDeptTel() {
		return deptTel;
	}

	public void setDeptTel(String deptTel) {
		this.deptTel = deptTel;
	}

	@Column(name = "DEPT_ADDRESS", nullable = false, length = 200)
	public String getDeptAddress() {
		return deptAddress;
	}

	public void setDeptAddress(String deptAddress) {
		this.deptAddress = deptAddress;
	}

	@Column(name = "DEPT_CODE", nullable = false, length = 200)
	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "DEPT_GRADE", nullable = false, length = 200)
	public String getDeptGrade() {
		return deptGrade;
	}

	public void setDeptGrade(String deptGrade) {
		this.deptGrade = deptGrade;
	}
    
    
    
	
    
    

}
