package com.hjkj.hyjc.model.admin;

// Generated 2016-7-28 22:05:05 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfFunctions generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_FUNCTIONS")
public class SysFunctions implements java.io.Serializable {
    /**
     * 比较方法
     * 
     * @param p
     * @return
     */
    public boolean equals(Object p) {
        SysFunctions fun = (SysFunctions) p;
        if (this == fun) {
            return true;
        }
        if (this.funId.equals(fun.getFunId())) {
            return true;
        } else {
            return false;
        }

    }

    private static final long serialVersionUID = 1L;
    private String funId;
    private int version;
    private String funName;
    private String funType;
    private Integer funLevel;
    private String linkPage;
    private String description;
    private String parentFunId;
    private int funIndex;
    private String display;
    private String memo;
    private String mark;
    private String maker;
    private Date maketime;
    private String updater;
    private Date updatetime;
    private String iconStyle;

    /**
     * 子菜单
     */
    private List<SysFunctions> subList = new ArrayList<SysFunctions>();

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "fun_id", unique = true, nullable = false)
    public String getFunId() {
        return this.funId;
    }

    public void setFunId(String funId) {
        this.funId = funId;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "fun_name", nullable = false, length = 200)
    public String getFunName() {
        return this.funName;
    }

    public void setFunName(String funName) {
        this.funName = funName;
    }

    @Column(name = "fun_type", nullable = false, length = 10)
    public String getFunType() {
        return funType;
    }

    public void setFunType(String funType) {
        this.funType = funType;
    }

    @Column(name = "fun_level", nullable = false, length = 10)
    public Integer getFunLevel() {
        return funLevel;
    }

    public void setFunLevel(Integer funLevel) {
        this.funLevel = funLevel;
    }

    @Column(name = "link_page", length = 500)
    public String getLinkPage() {
        return this.linkPage;
    }

    public void setLinkPage(String linkPage) {
        this.linkPage = linkPage;
    }

    @Column(name = "description", nullable = false, length = 1000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "parent_fun_id", length = 100)
    public String getParentFunId() {
        return this.parentFunId;
    }

    public void setParentFunId(String parentFunId) {
        this.parentFunId = parentFunId;
    }

    @Column(name = "fun_index", nullable = false)
    public int getFunIndex() {
        return this.funIndex;
    }

    public void setFunIndex(int funIndex) {
        this.funIndex = funIndex;
    }

    @Column(name = "display", nullable = false, length = 1)
    public String getDisplay() {
        return this.display;
    }

    public void setDisplay(String display) {
        this.display = display;
    }

    @Column(name = "memo", length = 500)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "mark", nullable = false, length = 1)
    public String getMark() {
        return this.mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    @Column(name = "maker", nullable = false, length = 50)
    public String getMaker() {
        return this.maker;
    }

    public void setMaker(String maker) {
        this.maker = maker;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "maketime", nullable = false, length = 19)
    public Date getMaketime() {
        return this.maketime;
    }

    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    @Column(name = "updater", nullable = false, length = 50)
    public String getUpdater() {
        return this.updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", nullable = false, length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Column(name = "icon_style", length = 100)
    public String getIconStyle() {
        return iconStyle;
    }

    public void setIconStyle(String iconStyle) {
        this.iconStyle = iconStyle;
    }

    @Transient
    public List<SysFunctions> getSubList() {
        return subList;
    }

    public void setSubList(List<SysFunctions> subList) {
        this.subList = subList;
    }

}
