package com.hjkj.hyjc.model.admin;
// default package

// Generated 2017-7-23 20:46:16 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfFile generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_FILE")
public class SysFile implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private String fileId;
    private String fileName;
    private String filePath;
    private String fileTable;
    private Integer filePid;
    private String fileSuffix;

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "file_id", unique = true, nullable = false)
    public String getFileId() {
        return this.fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    @Column(name = "file_name", length = 100)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "file_path", length = 100)
    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "file_table", length = 100)
    public String getFileTable() {
        return this.fileTable;
    }

    public void setFileTable(String fileTable) {
        this.fileTable = fileTable;
    }

    @Column(name = "file_pid")
    public Integer getFilePid() {
        return this.filePid;
    }

    public void setFilePid(Integer filePid) {
        this.filePid = filePid;
    }

    @Column(name = "file_suffix", length = 100)
    public String getFileSuffix() {
        return this.fileSuffix;
    }

    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix;
    }

}
