package com.hjkj.hyjc.model.admin;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfRoleFunction generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_ROLE_FUNCTION")
public class SysRoleFunction implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private String serialId;
    private int version;
    private String roleId;
    private String funId;

    public SysRoleFunction() {
    }

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "serial_id", unique = true, nullable = false)
    public String getSerialId() {
        return this.serialId;
    }

    public void setSerialId(String serialId) {
        this.serialId = serialId;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "role_id", nullable = false, length = 100)
    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    @Column(name = "fun_id", nullable = false, length = 100)
    public String getFunId() {
        return this.funId;
    }

    public void setFunId(String funId) {
        this.funId = funId;
    }

}
