package com.hjkj.hyjc.model.admin;

// Generated 2016-7-28 22:05:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfRole generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_ROLE")
public class SysRole implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private String roleId;
    private int version;
    private String roleName;
    private String memo;
    private String mark;
    private String maker;
    private Date maketime;
    private String updater;
    private Date updatetime;

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "role_id", unique = true, nullable = false)
    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "role_name", nullable = false, length = 50)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "memo", length = 500)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "mark", nullable = false, length = 1)
    public String getMark() {
        return this.mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    @Column(name = "maker", nullable = false, length = 50)
    public String getMaker() {
        return this.maker;
    }

    public void setMaker(String maker) {
        this.maker = maker;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "maketime", nullable = false, length = 19)
    public Date getMaketime() {
        return this.maketime;
    }

    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    @Column(name = "updater", nullable = false, length = 50)
    public String getUpdater() {
        return this.updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updatetime", nullable = false, length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

}
