package com.hjkj.hyjc.model.admin;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfUsers generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_USERS1")
public class SysUsers implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private String id;
    
    //年龄
    private Integer age;

	/**
	 * 生日
	 */
    private Date birthday;
    /**
	 * 用户中文名称
	 */
    private String cname;
    /**
	 * 用户英文名称
	 */
    private String ename;
    /**
	 * 公司邮箱
	 */
    private String companyMail;
    
    /**
	 * 用户创建日期(蓝图数据库创建日期)
	 */
    private Date createtime;
    /**
	 * 邮箱
	 */
    private String email;
    
    private Long evid;
    /**
     * 机构id
     */
    private String groupId;
    /**
	 * 家庭电话
	 */
    private String  homeTel;
    /**
	 * 身份证号码
	 */
    private String  idcard;

	/**
	 * 用户IP
	 */
	private String ip;
	
	/**
	 * 最后编辑日期
	 */
	private Date  lastedittime;
	
	/**
	 * 用户名称
	 */
	private String  loginName;
	
	/**
	 * 手机号
	 */
	private String  mobileno;
	
	/**
	 * 密码，经过加密后的
	 */
	private String  passWord;

	/**
	 * 性别
	 */
	private Integer sex;
	
	/**
	 * 创建这条记录的用户ID
	 */
	private Long  uCreateuserid;

	/**
	 * 用户编号
	 */
	private String  userno;
	
	/**
	 * 职称
	 */
	private Long  zc;
	
	/**
	 * 职务
	 */
	private Long  zw;
	
    /**
     * 备注
     */
    private String memo;
    /**
     * 标记
     */
    private String mark;
    /**
     * 创建人
     */
    private String maker;
    /**
     * 创建时间
     */
    private Date maketime;
    /**
     * 更新人
     */
    private String updater;
    /**
     * 更新时间
     */
    private Date updatetime;
    /**
     * 版本
     */
    private int version;
    
    
    private SysDepartment department;
    
    private SysRole role;

    public SysUsers() {
    }

   

    @Id
	@Column(length = 32)
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@GeneratedValue(generator = "uuid")
    public String getId() {
		return id;
	}




	public void setId(String id) {
		this.id = id;
	}



	@Column(length = 3,name="U_AGE")
	public Integer getAge() {
		return age;
	}




	public void setAge(Integer age) {
		this.age = age;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="U_BIRTHDAY")
	public Date getBirthday() {
		return birthday;
	}




	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}



	@Column(length = 20,name="U_CNAME")
	public String getCname() {
		return cname;
	}




	public void setCname(String cname) {
		this.cname = cname;
	}



	@Column(length = 50,name="U_ENAME")
	public String getEname() {
		return ename;
	}




	public void setEname(String ename) {
		this.ename = ename;
	}



	@Column(length = 255,name="U_COMPANYMAIL")
	public String getCompanyMail() {
		return companyMail;
	}




	public void setCompanyMail(String companyMail) {
		this.companyMail = companyMail;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="U_CREATETIME")
	public Date getCreatetime() {
		return createtime;
	}




	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}



	@Column(length = 100,name="U_EMAIL")
	public String getEmail() {
		return email;
	}




	public void setEmail(String email) {
		this.email = email;
	}



	@Column(length=32,name="EVID")
	public Long getEvid() {
		return evid;
	}




	public void setEvid(Long evid) {
		this.evid = evid;
	}



	@Column(length = 32 ,name="U_GROUPID")
	public String getGroupId() {
		return groupId;
	}




	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}



	


	@Column(length = 20,name="U_HOMETEL")
	public String getHomeTel() {
		return homeTel;
	}



	public void setHomeTel(String homeTel) {
		this.homeTel = homeTel;
	}



	@Column(length = 30,name="U_IDCARD")
	public String getIdcard() {
		return idcard;
	}




	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}



	@Column(length = 32)
	public String getIp() {
		return ip;
	}




	public void setIp(String ip) {
		this.ip = ip;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="U_LASTEDITTIME")
	public Date getLastedittime() {
		return lastedittime;
	}




	public void setLastedittime(Date lastedittime) {
		this.lastedittime = lastedittime;
	}



	@Column(length = 20,name="U_LOGINNAME")
	public String getLoginName() {
		return loginName;
	}




	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}



	@Column(length = 15,name="U_MOBILENO")
	public String getMobileno() {
		return mobileno;
	}




	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}



	@Column(length = 200,name="U_PASSWORD")
	public String getPassWord() {
		return passWord;
	}




	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}



	@Column(length = 1,name="U_SEX")
	public Integer getSex() {
		return sex;
	}




	public void setSex(Integer sex) {
		this.sex = sex;
	}



	@Column(name="U_CREATEUSERID")
	public Long getuCreateuserid() {
		return uCreateuserid;
	}




	public void setuCreateuserid(Long uCreateuserid) {
		this.uCreateuserid = uCreateuserid;
	}



	@Column(length = 20,name="U_USERNO")
	public String getUserno() {
		return userno;
	}




	public void setUserno(String userno) {
		this.userno = userno;
	}



	@Column(length = 2,name="U_ZC")
	public Long getZc() {
		return zc;
	}




	public void setZc(Long zc) {
		this.zc = zc;
	}



	@Column(length = 2,name="U_ZW")
	public Long getZw() {
		return zw;
	}




	public void setZw(Long zw) {
		this.zw = zw;
	}


	@Column(name = "memo", length = 500)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "MARK", nullable = false, length = 1)
    public String getMark() {
        return this.mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    @Column(name = "MAKER", nullable = false, length = 50)
    public String getMaker() {
        return this.maker;
    }

    public void setMaker(String maker) {
        this.maker = maker;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MAKETIME", nullable = false, length = 19)
    public Date getMaketime() {
        return this.maketime;
    }

    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    @Column(name = "UPDATER", nullable = false, length = 50)
    public String getUpdater() {
        return this.updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATETIME", nullable = false, length = 19)
    public Date getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    
    @Version
    @Column(name = "VERSION", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Transient
    public SysDepartment getDepartment() {
        return department;
    }

    public void setDepartment(SysDepartment department) {
        this.department = department;
    }

    @Transient
    public SysRole getRole() {
        return role;
    }

    public void setRole(SysRole role) {
        this.role = role;
    }

}
