package com.hjkj.hyjc.model.admin;

// Generated 2016-7-28 22:05:05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * EfUserDempartment generated by hbm2java
 */
@Entity
@Table(name = "T_SYS_USER_DEMPARTMENT")
public class SysUserDempartment implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private String serialId;
    private String deptId;
    private String userId;
    private String memo;

    public SysUserDempartment() {
    }

    @Id
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    @Column(name = "serial_id", unique = true, nullable = false)
    public String getSerialId() {
        return this.serialId;
    }

    public void setSerialId(String serialId) {
        this.serialId = serialId;
    }

    @Column(name = "dept_id", nullable = false, length = 100)
    public String getDeptId() {
        return this.deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    @Column(name = "user_id", nullable = false, length = 100)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "memo", length = 500)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

}
